version: "3.8"
services:
  app:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
    restart: always
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - IMAGE_NAME=${IMAGE_NAME}
      - IMAGE_TAG=${IMAGE_TAG}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
