export enum Label {
  Creative,
  Sports,
  Science,
  Professional,
  Consulting,
  Dance,
  Cultural,
  Entrepreneurship,
  Language,
  Volunteer,
  Music,
  Sustainability,
  Gaming,
  Technology,
  Wellness,
  Media,
  Political,
  Research,
  Social,
  Networking,
  Religious,
}

export enum SpecialtyLabel {
  Project_Team,
  Greek_Life,
  Competition,
  Application,
  Interview,
  Audition,
}

export enum Group {
  Wellness_Lifestyle = "Wellness & Lifestyle",
  Business_Entrepreneurship = "Business & Entrepreneurship",
  Sports_Hobby = "Sports & Hobby",
  Project_Teams = "Project Teams",
  Greek_Life = "Greek Life",
  Arts_Media = "Arts & Media",
  Technology_Science = "Technology & Science",
  Cultural_Community = "Cultural & Community",
  Law_Politics = "Law & Politics",
  ROTC = "ROTC",
  Other = "Other",
}

export enum Category {
  Finance = "Finance",
  Consulting = "Consulting",
  Investment = "Investment",
  Film = "Film",
  Creative_Writing = "Creative Writing",
  Crafts_DIY = "Crafts & DIY",
  Environmental = "Environmental",
  Food = "Food",
  Yoga_Meditation = "Yoga Meditation",
  Mental_Health = "Mental Health",
  Martial_Arts = "Martial Arts",
  LGBTQ = "LGBTQ",
  Robotics = "Robotics",
  AI = "AI",
  Electronics = "Electronics",
  Engineering = "Engineering",
  Astronomy = "Astronomy",
  Womens_Rights = "Womens Rights",
  Political = "Political",
  Religious = "Religious",
  Activism = "Activism",
  International = "International",
  Gaming = "Gaming",
  Anime = "Anime",
  Music = "Music",
  Dance = "Dance",
  Tutoring = "Tutoring",
  Theater = "Theater",
  Singing = "Singing",
  Sewing = "Sewing",
  Architecture = "Architecture",
  Visual_Arts = "Visual Arts",
  Performing_Arts = "Performing Arts",
  Photography = "Photography",
  Outdoor_Adventure = "Outdoor Adventure",
  Fashion = "Fashion",
  Design = "Design",
  Real_Estate = "Real Estate",
  Prelaw = "Prelaw",
  Premed = "Premed",
  Law = "Law",
  Prevet = "Prevet",
  Philosophy = "Philosophy",
}

export enum Attributes {
  Membership = "Membership Only",
  Virtual = "Virtual",
  In_person = "In Person",
  Application_Interview = "Application/Interview",
  Small = "Small",
  Medium = "Medium",
  Large = "Large",
  Volunteer = "Volunteer",
  Competitions = "Competitions",
  Training = "Training",
  Sponsorship = "Sponsorship",
  Open_to_All = "Open to All",
}
