name: CI + CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: "clubspace"
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: clubspace
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Configure environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build container image
        run: docker build --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_PASSWORD,IMAGE_NAME,IMAGE_TAG,REDIS_PASSWORD
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/clubspace
            git clone git@github.com:mikeyliang/clubspace
            cd clubspace
            echo "DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}" >> .env
            echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> .env
            echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> .env
            echo "${{ secrets.ENV_FILE }}" >> .env
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d
            cd ..
            rm -rf clubspace
